const {
  PORT: PORT_DEV,
  DB: DB_DEV,

  JWT_SECRET: JWT_SECRET_DEV,
  JWT_EXPIRES_IN: JWT_EXPIRES_IN_DEV,

  RATE_LIMIT_WINDOW: RATE_LIMIT_WINDOW_DEV,
  RATE_LIMIT_MAX: RATE_LIMIT_MAX_DEV,
} = require('../config.dev.json');

const {
  PORT = PORT_DEV,
  DB = DB_DEV,

  JWT_SECRET = JWT_SECRET_DEV,
  JWT_EXPIRES_IN = JWT_EXPIRES_IN_DEV,

  RATE_LIMIT_WINDOW = RATE_LIMIT_WINDOW_DEV,
  RATE_LIMIT_MAX = RATE_LIMIT_MAX_DEV,
} = process.env;

module.exports = {
  PORT,
  DB,

  JWT_SECRET,
  JWT_EXPIRES_IN,

  RATE_LIMIT_WINDOW,
  RATE_LIMIT_MAX,
};
